Repository sailfishos-patches/patchmanager, pull requests merged in 2021-11, with the labels that each got.

#139 Fix settings-patchmanager.ts
  translations/settings-patchmanager.ts
Labels: trivial

#156 Web Catalog Page: translate category also in regular view
  src/qml/WebCatalogPage.qml
Labels: trivial

#153 Translate Category names in ENglish
  translations/settings-patchmanager.ts
Labels: debt

#136 Show list of things to be restarted on the "Restart Services" dialog
  src/bin/patchmanager-daemon/dbus/org.SfietKonstantin.patchmanager.xml
  src/bin/patchmanager-daemon/patchmanagerobject.cpp
  src/bin/patchmanager-daemon/patchmanagerobject.h
  src/qml/RestartServicesDialog.qml
  src/qml/patchmanager.cpp
  src/qml/patchmanager.h
  translations/settings-patchmanager.ts
Labels: UX

#200 Trivial fixes for various UI complaints
  src/qml/UnifiedPatchPage.qml
Labels: trivial, debt
