Repository sailfishos-patches/patchmanager, pull requests merged in 2021-12, with the labels that each got.

#199 [ui] Add option to suppress notifications
  src/bin/patchmanager-daemon/patchmanagerobject.cpp
  src/qml/SettingsPage.qml
  src/qml/patchmanager.cpp
  src/qml/patchmanager.h
Labels: backends, UX, patching

#217 [pm_apply] Fix manglelist path
  src/tools/pm_apply
Labels: bug, #fixed, trivial

#219 [pm_apply] Fix case of empty MANGLE_CANDIDATES
  src/tools/pm_apply
Labels: bug, #fixed

#216 [pm_apply] Slightly enhance log output
  src/tools/pm_apply
Labels: enhancement, trivial, UX, patching
