Repository sailfishos-patches/patchmanager, pull requests merged in 2022-01, with the labels that each got.

#227 Strings rework
  src/bin/dialog/dialog.qml
  src/bin/patchmanager-daemon/patchmanagerobject.cpp
  src/qml/AboutPage.qml
  src/qml/DevelopersPage.qml
  src/qml/PatchManagerPage.qml
  src/qml/PatchObject.cpp
  src/qml/RestartServicesDialog.qml
  src/qml/SettingsPage.qml
  src/qml/UnifiedPatchPage.qml
  src/qml/WebCatalogPage.qml
  src/qml/WebPatchPage.qml
  translations/settings-patchmanager.ts
Labels: bug, translation, UX

#236 Update wording to the consolidated nomenclature
  doc/example_legacy_patch.json.md
Labels: debt, documentation

#235 Update wording to the consolidated nomenclature
  doc/example_patch.json.md
Labels: debt, documentation

#234 [README.md] Update wording to the consolidated nomenclature
  README.md
Labels: debt, documentation

#228 [pm_unapply] Enhance checks&balances and debug output
  src/tools/pm_unapply
Labels: enhancement, trivial, UX, patching

#225 [pm_apply] Do convert multiple libpath references
  src/tools/pm_apply
Labels: enhancement, debt

#241 [pm_apply] improve mangling by patching outside the loop
  src/tools/pm_apply
Labels: enhancement, patching

#240 l18n: Adapt to bitness nomenclature and fix all line number references
  src/bin/dialog/dialog.qml
  src/bin/patchmanager-daemon/patchmanagerobject.cpp
  src/qml/SettingsPage.qml
  src/qml/patchmanager.cpp
  translations/settings-patchmanager.ts
Labels: bug, translation, patching

#247 settings-patchmanager.ts: Fix broken XML tag
  translations/settings-patchmanager.ts
Labels: bug, translation

#248 update translation source
  src/bin/patchmanager-daemon/patchmanagerobject.cpp
  translations/settings-patchmanager.ts
Labels: bug, translation
