Repository sailfishos-patches/patchmanager, pull requests merged in 2023-01, with the labels that each got.

#324 Enhance GitHub issue-templates
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/help-template.md
  .github/ISSUE_TEMPLATE/suggestion-template.md
Labels: enhancement

#323 Missed to increase version for ~3.2.3~, now 3.2.4
  rpm/patchmanager.spec
Labels: bug, enhancement

#326 Use modern statements in spec file
  rpm/patchmanager.spec
Labels: enhancement

#334 Split "Allow incompatible Patches" from "Developer Mode"
  src/qml/PatchManagerPage.qml
  src/qml/SettingsPage.qml
  src/qml/WebPatchPage.qml
  src/qml/patchmanager.cpp
  src/qml/patchmanager.h
  src/qml/plugin.cpp
Labels: enhancement

#330 Update / Overhaul CI configuration
  .github/workflows/ci_sfos.latest-aarch64-armv7hl-i486.yml
  .github/workflows/ci_sfos3.4.0-armv7hl.yml
  .github/workflows/ci_sfos3.4.0-i486.yml
  .github/workflows/ci_sfos4.0.1-aarch64.yml
  rpm/patchmanager.spec
  src/tools/pm_apply
Labels: enhancement

#337 Really stick to new nomenclature, plus …
  .github/workflows/ci_sfos3.4.0-armv7hl.yml
  src/bin/patchmanager-daemon/main.cpp
  src/bin/patchmanager-daemon/patch/patch.json
  src/bin/patchmanager-daemon/patchmanagerobject.cpp
  src/qml/PatchManagerPage.qml
  src/qml/SettingsPage.qml
  src/tools/pm_apply
  src/tools/pm_unapply
Labels: enhancement

#391 [CI workflow] Consolidate into two
  .github/workflows/ci-on-pull_req.yml
  .github/workflows/ci-on-tags.yml
  .github/workflows/ci_sfos-latest-aarch64-armv7hl-i486.yml
  .github/workflows/ci_sfos3.4.0-armv7hl.yml
  .github/workflows/ci_sfos3.4.0-i486.yml
  .github/workflows/ci_sfos4.0.1-aarch64.yml
Labels: bug, #fixed

#394 [CI workflows] Omit "Prepare" step
  .github/workflows/ci-on-pull_req.yml
  .github/workflows/ci-on-tags.yml
Labels: enhancement

#397 Beautify CI output & sh_mb2 script
  .github/workflows/ci-on-pull_req.yml
  .github/workflows/ci-on-tags.yml
Labels: enhancement

#395 [spec file] Insert dummy changelog with a correct entry
  rpm/patchmanager.spec
Labels: enhancement

#396 [README] Overhaul paragraph "How to install Patchmanager"
  README.md
Labels: enhancement, documentation

#403 Overhaul rpmlintrc file
  rpm/patchmanager-rpmlintrc
Labels: enhancement
